### PR TITLE
Notes for lec 1

### PR DESCRIPTION
**Pull request by rivajw**
Not sure how to have a branch with only lec 1 notes. The current pull request contains the completed lec01_worksheet.

### CODE REVIEW

**Comment by gallettilance** [comment]
nice work! Can you please put your notes and worksheets into the `student notes/` folder? Then I will be able to merge your PR :)

**Comment by rivajw** [comment]
Moved the notes into the correct folder.

**Comment by gallettilance** [comment]
Thanks! Almost ready to merge - can you move your worksheets there too (or undo the changes to the worksheet files? (otherwise everyone will see your completed worksheets instead of the uncompleted worksheets to be completed by students)

**Comment by rivajw** [comment]
The worksheet has been undone.

**Comment by gallettilance** [comment]
nice work! looks like worksheet 0 is still modified in the `lecture_00/` folder - almost there!

**Comment by rivajw** [comment]
All done! Sorry for the inconvenience.

**Comment by gallettilance** [comment]
No need to apologies! Amazing work!

**Pull request merged**
