### PR TITLE
worksheet 5

### PR DESCRIPTION
**Pull request by 2emily3**

### CODE REVIEW

**Review by gallettilance — CHANGES_REQUESTED** [review]
nice work! please undo the changes to the `lecture_xx/worksheets`

**Comment by 2emily3** [comment]
Okay, I just did that for worksheet 4, 5, and 7

**Review by gallettilance — CHANGES_REQUESTED** [review]
please don't delete the worksheets from lecture 04 and 07 - please instead reset them back to the uncompleted version

**Review by gallettilance — CHANGES_REQUESTED** [review]
please un-delete the worksheets from the lecture folders.

**Pull request closed without merging**
